laguage: go

services:
  - docker
  
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}"
  - export TRAVIS_BUILD_DIR="${GOPATH}/src"
  - mkdir -p $TRAVIS_BUILD_DIR

script:
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push docker.io/guiferpa/gcd;
    fi
