laguage: go

services:
  - docker
  
install:
  - echo $TRAVIS_BUILD_DIR
  - export TRAVIS_BUILD_DIR=~/Projects/stone-payments/gcd
  - echo $TRAVIS_BUILD_DIR

script:
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push docker.io/guiferpa/gcd;
    fi
