laguage: go

services:
  - docker
  
before_install:
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/stone-payments/gcd
  - cd $GOPATH/src/github.com/stone-payments/gcd

script:
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push docker.io/guiferpa/gcd;
    fi
