laguage: go

services:
  - docker
  
go_import_path: github.com/stone-payments/gcd

script:
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push docker.io/guiferpa/gcd;
    fi
