laguage: go

services:
  - docker
  
before_install:
  - mkdir -p $GOPATH/src/github.com/stone-payments/gcd
  - mv $TRAVIS_BUILD_DIR $GOPATH/src/github.com/stone-payments
  - cd $GOPATH/src/github.com/stone-payments/gcd

script:
  - make
